services:
  api:
    container_name: api
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/rails"
    environment:
      - DATABASE_PASSWORD=tuj
    tty: true
    stdin_open: true
    depends_on:
      - db
    networks:
      - course-manager-network

  db:
    container_name: db
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      - "MYSQL_DATABASE=course-manager_development"
      - "MYSQL_USER=tuj"
      - "MYSQL_PASSWORD=tuj"
      - "MYSQL_ROOT_PASSWORD=root"
    networks:
      - course-manager-network

volumes:
  db-data:

networks:
  course-manager-network:
    external: true
