services:
  api:
    container_name: api
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/rails"
    environment:
      - DATABASE_PASSWORD=postgres
    tty: true
    stdin_open: true
    depends_on:
      - db
    networks:
      - course-manager-network

  db:
    container_name: db
    image: postgres:16.0
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DATABASE=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_ROOT_PASSWORD=root"
    networks:
      - course-manager-network

volumes:
  db-data:

networks:
  course-manager-network:
    external: true
