default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: db
  username: tuj
  port: 3306
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: course-manager_development

test:
  <<: *default
  database: course-manager_development

production:
  <<: *default
  # database: path/to/persistent/storage/production.sqlite3
